server:
  port: ${PORT}
app:
  external:
    btc:
      url: https://api.coindesk.com
spring:
  profiles:
    active: dev
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    enabled: true
    locations: classpath:db/migration/postgres
    url: "jdbc:postgresql://${DB_SERVER}:${DB_SERVER_PORT}/${DB_NAME}?sslMode=${DB_SSL_MODE:require}"
    user: ${DB_USER}
    password: ${DB_PASS}
  datasource:
    hikari:
      connectionTestQuery: SELECT 1
      poolName: pool
      maximumPoolSize: 50
      minimumIdle: 1
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_SERVER:localhost}:5432/${DB_NAME:dev}
    username: ${DB_USER:root}
    password: ${DB_PASS:toor}
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        time_zone: ${TIME_ZONE:UTC}
      org:
        hibernate:
          envers:
            default_schema: public
            store_data_at_delete: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    output:
      ansi:
        enabled: ALWAYS
  h2.console.enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    loggers:
      enabled: true
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
